<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BlogXpriya</title>
</head>

<body>
    <header>
        <!-- Intro settings -->
        <style>
            #intro {
                /* Margin to fix overlapping fixed navbar */
                margin-top: 58px;
            }
            .card-img{
                height: 320px;
            }
            @media (max-width: 991px) {
                #intro {
                    /* Margin to fix overlapping fixed navbar */
                    margin-top: 45px;
                }
            }
        </style>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
            <div class="container-fluid">
                <!-- Navbar brand -->
                <a class="navbar-brand" target="_blank" href="https://mdbootstrap.com/docs/standard/">
                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASoAAACpCAMAAACrt4DfAAAAvVBMVEX///9nZ2f/bAD/aQBaWlr/YAD/59r/lVzs7OxgYGD/h0b//vxkZGT/dBf/jlD/gj+vr6+mpqZ9fX1WVlb/ZQDy8vL/XQCZmZnR0dHDw8PLy8tzc3PX19eJiYn4+PiAgIDk5OS4uLj/+fStra2goKD/8Of/1cH/3s7/uJaRkZHe3t7/zbj/w6f/q4X/vJ7/gDb/eSr/oHL/qH7/4tNHR0f/mWf/v6X/fS7/k1f/0Lv/upn/l2X/n2//i0z/sI2yzBUGAAAL/UlEQVR4nO2da2OiOhCGVaCVittWEO8XWm3X2q52e
                    /babf//zzogAZKZBHGXYKi8H/qhmEAek8nMJJharVIlhXR2//3pvET6/P1+eQRMy99vjmE4jlYiOcETf/pSKK7WeuM6WqOU0hz3cl0YqceGUVJOoTSjUQys+7Zx7Lb+szTjx5l8Ul/dUveoSJr7LhnUzYVD3S6wk2WSQxtY46dcUu2YlGYYb+/r+5ez0ujl/vH9wkhoOZuWTFLRfTR/GrmRdyN5unn8Ec9Jzg9597mM+pSxuZd3F9m620bNcD7JusdzTOq3rFsUo3c3asiTnBvcuZE1f5Fzg+J0F/k7hpymNMgYd44RSOWsF8JKa8uo/QsZfkYBzpt8Rf3KeJRQuSOx7iPoczQG8696HVatXeRRWXdKqzvNo85DtQ3tiZH/XP6m5WcHm
                    //ZjK5zqPNgkSGofcu74lY4/WmbPCpr6nVa5lUelR4s0q1yH4H34XfgJJaqyVc30J4RpQaqz46caep7WK8bOwrN//Q0mfXR6now51emBiriMDh5567+hKi0+B+guViWZZq62XvgVKYGqlbYJOdPzvVuNGCq9qIiwPRRH1WmBqpaO/z23/KuVgOuQkZUAaxOF1SmCKoNbFM+It9AEopnRhXAGrOVKYLqUj1U9brNDsIKVYr0Jl1ZhSpF1oiurEKV2q2GVGUVqszdqkKV3q0oa3XqqMwkqDE5qEyvJip7aqj89u5yT93ufLiwMCyrVxOVPUFUlBZoeFqzmqjsaaOqXcN+Rdv1g1BNu0Fq56BE6dQvkaGAIqhqVg6oHrzeSLdt3/z5f+qT2
                    36G9vev/SJBCX20wIE6I1VQwW51MKr+ytRNiyJu+RPHbJBKq7kIylCf7839/171GA2iT6uCagyuH2irvLoO+yVp/gLmKWJ1V6iMpU+aNcsnnkiPM/mqoILXrYXwGkY15Eyh8ad1wXgd8OHqPfbfpnKo5vD6oCYqi1Ct0t1bc9SsYfVEhQBA9VDBAahT4yYdVbMu7lKk8To22JN9hdRFdcU+Om2q0lE1Td44ArIH7N1qq6ykFEQ1YhvM9IM0VJlIoWThVfaIVDlUHuhUHfpiGipoWoSs5lShuZ2ZlHKoPHCVaVgaqswDyapTFY4y8lUEVZI5mA5GoME6a1rEqPo4dgwzFnhYmon3Ab+YsKBl+sIMj4/K6qx2mszqNnxA/ZatTIwKtUwfeQ
                    /d6XQ+mCAcSU/l9ERT7yyuvKvFzITe1vFR1WN3GD61ZXugMiEqDzaa6o4P0IpZE3JlgFBZphf7Jg8L1VxQofTRHFYmRAUxMwuIU8gq6lbIUpkTOlKcgrspi4qzDi9ENYRuq5dWLIqVYFxQN1dMsW5ZUNV7AxTfilBN2O7Broj5uoWzxe6/Vyk5jEDlQeVPYZNsC/FT2KmGbDH8gV29HTiJzNlS5UEV0NJnWVaXoadgoqdYcSw05Bdb+0ilQgVnQQEqkA2kFy6IhuATwVB74HY1SiVD5bdg/4oNGEkmHH+o1XV9il0F1BdLh4pmJUAFjTYnKwXrnOO+uIJl1ENFJ2X5rDxBWYIKdhlsqtAcGXQ8aL9QjlQ5VNZoMpnMAnU6o7rOS97aTX5
                    Z0jrkH3EeA3rePv3ZvmGrHCqTcRen4x6GFY8NPiqQN2XzNkTAhwqaDSwcsuoKooIdv9lBoVlkffio4PQGJ/1AMA22wDnEOSyjPipkWJKelw0Vss81NN0F/sSHQIVXmGfcsqQoxJAF1eqjoEI5FZNb9h9Q9bCtQu8UlAIVmtOIsfp7W8VBNSu/WQ+EUD3wypKiIARklsMieXgGhH5VCZwFHiqU1BzzyvL9KpSCCQRc82Ce4LharMqJyuzzygq8dYtTIdx/MMT+g/qBDQ8VzI+k9yo4XHXOlheODR+WLlzmoYL5kWgmz5ZZwAYaR9RTPHeon4ThoVrAAWh3eWWjouDj5i2qkBsmpmzk2qkMqKDxic2PABUvcccK7hnZ5XVQwhjMgcqt2HBQ
                    wTbErpIotw52HmBvEtQXOgZwcQI47F2YuFEPFSdcTo8BkTeJnFCY8LR3y33IItKLYt1b9VaXgT/DS8LEc5oIFUQBLPQULi8Tv4CzL6F+3Z8352NvouPv6+iorN5wEMrzridop8DuIxN+2aRDIj+M8Rdm0CgRkmgEBiVN/qYQFVDVdxtPiPgZ43g/hhAVWv00k36FBnRs9rsH7K5SAtX+Z+wJyiaopjgbOBkGPYuXVU2GZy/z7sayoJoKylIzwoC3v8pnxMnVU0YfRQUlR2U/iMrSkye0R2Lp1G4XTFgs9VHZlGOYgmoqWBnD9TE7bA4Ygqqjsuys7y6j2IUv+ErELOX1iVKhMq05XVnqvvVxlvkseVEmEt4AGYEa43SgsqgsHWzUSH8b4
                    mH/znWbE5tf2TxXTl+pFwOmgOrAWG7POzZdHBKxNZrcF/3mMzhN+rcep9xNLVSWacN9aLgsjrQ9WwzLsieidwIfVomDbsW3BtYvicAKQ2Vb6QpCC2vFfdURlOXlbxbcoKQebLLm/SJWrP7tZPduvtVZDMmtwfJGsk5RGKpRR6zZZLW4GoxFLznCsmjlwNfUG7EvmYbe6GJ+8KOD5HuS2ikKVQFqDnoj0w5+t2EX+9ZXXmqHEgnkq+y4n38gVDt15+N+vz+e896WzCS0VzS+8tFQ/bNuhYtfFSpWKAWZvIpymqiuRiv+jyo00dsmyVxzmqiuTUvXe/gnKzzklVJLX6eKKnQmZrf92P53+wv8m0f0i8EnjCqkpZuj2WwyG1k8J5Z5N/W0UY
                    U8UjaE07mgClWK2EX6ClWK2M01FSqxbDbJUaESkwL7PmSh0sqOCv2SsixUP+CPiKul/aj0GUoJbeWgIqdoSDkhJwftQWXpdfxyYS1skpb34XfkIAVX0ePbbm2YB6Q4mXqHA6q2JAce5H2A2JqcOXGXc715aRr8hGHgqpux+xklrSceP9dFTubJ/SCbZXg4i/Occ735qjke3Pb8oGYUoBrNVguvL04J/iQn8+Q+UNqyKj6WyJevXeZe8zs5n0PSiXrFi5x26HzJvWbyJXyQg9xqtRfSHkfCMPlGTrLZ5l/1EdQiBkWK8Y26lSP3EN6CFB2KLMf2PpHanXMZtRerTxGpz3Lqj44Sdi5LPg0uozNypQVqy+igRs0p9dGTX5KTl6Udyxqdket
                    33G3e558VpdZjO/rGG67E06PXMSvN0J5/LSWeHC5DreX6jxN3KclR2i83OZDeMQxtu7koRq8HN2v5DKrYtDXDiM+4979syfHsWSO5WXC/wuQeGCb8dh1UB/3kTkP68dGtV5e5ZWFyDwkTlpdGamWaW0jcf781jgHrkFn3Mf0JNWMj0aAzWm9cJ+1RpMj4lfXxbj6ldSnNcS8yV5WDXp7ahuNoRfYuN6tt+eWIHkvTHMdtvxce8C/XTz+3bf/mkhW3O9tj3bwmDo3DPJ3W/nH+tJZuzMVqydZhS5B3yQztNO6Zp5MMQgHdkNWC9ywffo67VMP9cwJwWJGz3LM4jC9Ul3JUXTCRqOh88v1G5inx+Izzkic//krnGU+9P9vGXUrL/TDzckjL
                    ZtU/U13q7RS7VLIAmZ6uXG5ir1Mzvhf0aKrpVxarTgUyxuaIntNxRdYf03z1m7ekS7mSkuVl0Nteq75OupSz/SCrlH8lYtWFq0Q351Rm9sMsff+Nop09onF1pzGBzClrj1WnAhnjT7FPppyIVecvAtOBjHaCgQyrtI2VJx/IsCJW/RVfqQIZVpFVx5ugqkAGSLRfkwlkSr0rIDc98a06Hchcnmwgw+oi3IXPWvUqkOGJ7BT8Rv+vCmR4OnORVadXZA5dnP/Iil4sSKx6FcgI9BVadXpF5vnkVmTSdMla9fsqkBGKmCoSCNOBzGvldTI6I776LlleBTJpIlbdfalVgcweRVa9xQQy5d7eLEmb0KpvqxWZfWoRX/31JxUbV4EMT8SqN7Qqk
                    NmnR7CLsgpkhPrKonIaL8d+ImW1YfZ0Gmq/Nn1UtehOVQUyaXqhtlRXgUyqEquuZd+zfpp6jlBVgcw+kQmwWpHZr/D1/iqQyaK1YxhG3j9u80HVururrFSlj63/AWk8KYwPuIH8AAAAAElFTkSuQmCC" height="32" alt="" loading="lazy" style="margin-top: -3px;" />
                </a>
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01" aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarExample01">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="index">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="login" target="_blank">Login</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav d-flex flex-row">
                        <!-- Icons -->
                        <li class="nav-item me-3 me-lg-0">
                            <a class="nav-link" href="https://www.youtube.com/channel/UC5CF7mLQZhvx8O5GODZAhdA" rel="nofollow" target="_blank">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </li>
                        <li class="nav-item me-3 me-lg-0">
                            <a class="nav-link" href="https://www.facebook.com/mdbootstrap" rel="nofollow" target="_blank">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li class="nav-item me-3 me-lg-0">
                            <a class="nav-link" href="https://twitter.com/MDBootstrap" rel="nofollow" target="_blank">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li class="nav-item me-3 me-lg-0">
                            <a class="nav-link" href="https://github.com/mdbootstrap/mdb-ui-kit" rel="nofollow" target="_blank">
                                <i class="fab fa-github"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Navbar -->

        <!-- Jumbotron -->
        <div id="intro" class="p-5 text-center bg-light">
            <h1 class="mb-3 h2">Learn Bootstrap 5 with MDB</h1>
            <p class="mb-3">Best & free guide of responsive web design</p>
            <a class="btn btn-primary m-2" href="https://www.youtube.com/watch?v=c9B4TPnak1A" role="button" rel="nofollow" target="_blank">Start tutorial</a>
            <a class="btn btn-primary m-2" href="https://mdbootstrap.com/docs/standard/" target="_blank" role="button">Download MDB UI KIT</a>
        </div>
        <!-- Jumbotron -->
    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center">
                <h4 class="mb-5"><strong>Latest posts</strong></h4>

                <div class="row">
                    <?php
                    foreach ($posts as $post) {
                        echo '<div class="col-lg-4 col-md-12 mb-4">
                            <div class="card">
                                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                    <img src="img/thumbnail/' . $post->post_img . '" class="img-fluid card-img" />
                                    <a href="#!">
                                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                    </a>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">' . $post->post_title . '</h5>
                                    <p class="card-text">
                                    ' . substr_replace($post->thumbnail, "...", 150) . '
                                    </p>
                                    <a href="index/singleBlog" class="btn btn-primary">Read</a>
                                </div>
                            </div>
                        </div>';
                    }
                    ?>
            </section>
            <!--Section: Content-->

            <!-- Pagination -->
            <nav class="my-4" aria-label="...">
                <ul class="pagination pagination-circle justify-content-center">
                    <li class="page-item">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="bg-light text-lg-start">
        <hr class="m-0" />
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!--Footer-->
</body>

</html>